<?php
$data = json_decode('{"timestamp":"2026-03-24 15:09:54","data":{"form":{"id":"9df0fca","name":"New Form"},"fields":{"name":{"id":"name","type":"text","title":"Full Name *","value":"Mostafa Osama","raw_value":"Mostafa Osama","required":"1"},"email":{"id":"email","type":"tel","title":"Phone Number*","value":"+201129274930","raw_value":"+201129274930","required":"1"},"field_f4c004c":{"id":"field_f4c004c","type":"email","title":"Email Address *","value":"mostafaweb27@gmail.com","raw_value":"mostafaweb27@gmail.com","required":"1"},"field_70a4eab":{"id":"field_70a4eab","type":"text","title":"Property Type *","value":"buy","raw_value":"buy","required":"1"},"field_d91170a":{"id":"field_d91170a","type":"text","title":"Community \/ Area *","value":"dubai","raw_value":"dubai","required":"1"},"field_03c4f85":{"id":"field_03c4f85","type":"text","title":"Asking price (AED)*","value":"20","raw_value":"20","required":"1"},"field_5d714be":{"id":"field_5d714be","type":"text","title":"Preferred Contact Method","value":"test","raw_value":"test","required":"1"},"field_3d9232c":{"id":"field_3d9232c","type":"text","title":"Property Description","value":"test","raw_value":"test","required":"1"},"message":{"id":"message","type":"upload","title":"Upload Images \/ Documents (optional)","value":"https:\/\/remaxzam.ae\/wp-content\/uploads\/elementor\/forms\/69c29b257e773.jpg","raw_value":"\/home\/q36ewq8leznn\/public_html\/wp-content\/uploads\/elementor\/forms\/69c29b257e773.jpg","required":"0","file_sizes":"","file_types":"","max_files":"","attachment_type":"link"}},"meta":{"date":{"title":"Date","value":"March 24, 2026"},"time":{"title":"Time","value":"2:09 pm"},"page_url":{"title":"Page URL","value":"https:\/\/remaxzam.ae\/list-your-property\/"},"user_agent":{"title":"User Agent","value":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/146.0.0.0 Safari\/537.36"},"remote_ip":{"title":"Remote IP","value":"197.38.44.135"},"credit":{"title":"Powered by","value":"PRO Elements"}}}}', true);

echo "Sending to list_your_property.php...\n";
$ch = curl_init('http://localhost:8080/list_your_property.php');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
$resp = curl_exec($ch);
echo "Response: " . $resp . "\n";
curl_close($ch);
